### ISSUE TITLE
StackOverflowError when starting repl

### ISSUE THREAD

**Issue by Gonzih** [tomjakubowski/weasel#34]
Hi, I tried to integrate weasel in to my current problem and got stuck with some weird error.

I have pretty big folder with bunch of clojurescript namespaces that use reagent.
Without this folder everything works fine.
With this namespace I'm getting error:

```
StackOverflowError   clojure.lang.AFn.applyToHelper (AFn.java:148)
```

Funny enough, when I remove all files from this folder, except main one (core.cljs) I'm getting different error:

```
StackOverflowError   clojure.lang.Murmur3.hashUnencodedChars (Murmur3.java:76)
```

There are no warning or compilation errors in cljsbuild for my code, everything works like a charm.
Any tips where I should look for the solution?
Thanks!

**Comment by tomjakubowski** [comment]
Sorry for the late response: @Gonzih were you able to sort this out?

If you don't know (it's been a while since your last comment!) you can avoid the hassle of installing modified dependencies to a local Maven repository by using Leiningen's brilliant [checkout dependencies](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#checkout-dependencies) feature.

**Comment by Gonzih** [comment]
No, sorry. I tried with few releases without much success. Latest 
release of figwheel includes built in repl, so I'm happily using it 
nowadays. I think this issue can be closed. Thanks!
